### ISSUE TITLE
I/O operation on closed file。I am looking forward your reply! thank you so much！！！

### ISSUE THREAD

**Issue by ccchen091** [facebookresearch/assemblyhands-toolkit#14]
Traceback (most recent call last):
  File "/data/d2/chenhao/code/assemblyhands/src/dataset/AssemblyHands-Ego/dataset.py", line 648, in <module>
    tester._make_batch_generator(args_test_set, shuffle=True)
  File "/data/d2/chenhao/code/assemblyhands/src/common/base.py", line 163, in _make_batch_generator
    testset_loader = Dataset(transforms.ToTensor(), self.cfg, test_set)
  File "/data/d2/chenhao/code/assemblyhands/src/dataset/AssemblyHands-Ego/dataset.py", line 191, in __init__
    f.write(f"{file_name},{hand_id}\n")
ValueError: I/O operation on closed file.

**Comment by pcc03** [comment]
Hi,
I also encountered this problem. Could I know how you solve it?

**Comment by gom-pang** [comment]
Hi, I solve that probelm. :)

src/dataset/AssemblyHands-Ego/dataset.py, line 413
self.cfg -> self.cfg.**vis_dir**
